import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/theme-provider";
import AppLayout from "@/components/AppLayout";

export const metadata: Metadata = {
  title: "Pushkaraj Suryawanshi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`h-screen w-screen antialiased`}
    >

      <body className="h-full w-full bg-primary">
        <Providers>
          <AppLayout>
            {children}
          </AppLayout>
        </Providers>
      </body>
    </html>
  );
}
