import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/theme-provider";
import ThemeToggle from "@/components/theme-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`h-screen w-screen antialiased`}
    >

      <body className="h-full w-full flex bg-primary">
        <Providers>
          {/* Navbar */}
          <nav className="w-1/9 h-full p-7">
            <div className="h-full w-full rounded-full neu-card"></div>
          </nav>
          {/* Main Screen */}
          <main className="h-full">{children}</main>
          {/* Theme toggle button */}
          <ThemeToggle />
        </Providers>
      </body>
    </html>
  );
}
