import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-screen w-screen dark antialiased`}
    >
      <body className="h-full w-full flex bg-primary">
        <nav className="w-1/9 h-full bg-accent"></nav>
        <main className="h-full">{children}</main>
      </body>
    </html>
  );
}
